version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: dbsf
      MYSQL_USER: django
      MYSQL_PASSWORD: django-user-password
      MYSQL_ROOT_PASSWORD: root
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db