version: '3'
services:
  db:
    image: mysql:latest
    volumes:
      - ./db:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: dbsf
      MYSQL_USER: django
      MYSQL_PASSWORD: django-user-password
      MYSQL_ROOT_PASSWORD: root
    expose:
      - "3306"
    networks:
      mynetwork:
        aliases:
          - db

  web:
    build: .
    command: bash -c "sleep 10 && python3 /DBSF/src/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      mynetwork:
        aliases:
          - web
networks:
  mynetwork:
  