# Generated by Django 4.1.7 on 2023-04-23 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Scans',
            new_name='Scan',
        ),
        migrations.RenameModel(
            old_name='ScanResults',
            new_name='ScanResult',
        ),
    ]
