# Generated by Django 4.1.7 on 2023-04-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_rename_scans_scan_rename_scanresults_scanresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='PacketRequest',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
