# Generated by Django 4.1.7 on 2023-05-29 09:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_remove_scanresult_filepath_scanresult_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='Created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
